# Generated by Django 4.2.5 on 2024-04-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_alter_freelancer_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='direction',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='directions',
            field=models.ManyToManyField(blank=True, choices=[('web', 'Веб-разработка'), ('mobile', 'Мобильная разработка'), ('design', 'Дизайн'), ('translater', 'Переводчик')], to='freelancer.direction'),
        ),
    ]
