# Generated by Django 4.2.5 on 2024-04-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_direction_remove_freelancer_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='directions',
            field=models.ManyToManyField(blank=True, null=True, to='freelancer.direction', verbose_name='Направления'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='experience',
            field=models.IntegerField(blank=True, choices=[(1, 'Менее 1 года'), (2, '1-3 года'), (3, '3-5 лет'), (4, 'Более 5 лет')], null=True, verbose_name='Опыт'),
        ),
    ]
