# Generated by Django 4.2.5 on 2024-04-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_freelancer_contact_info_alter_freelancer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='directions',
            field=models.ManyToManyField(blank=True, to='freelancer.direction', verbose_name='Направления'),
        ),
    ]
