version: '3'
services:
  db:
    image: postgres:16
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - web-network

  web:
    restart: always
    build: .
    command: sh -c "sleep 2 && gunicorn anverali_test.wsgi:application -w 4 -b 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - web-network

networks:
  web-network: